# frozen_string_literal: true

require "rails/generators"
require "digest"
require "erb"
require "fileutils"
require "json"

module PiBrowserTaskbar
  module Generators
    class InstallGenerator < ::Rails::Generators::Base
      desc "Install, update, or uninstall the development-only Pi Browser Taskbar Rails integration"

      class_option :layout, type: :string, desc: "Project-relative ERB application layout"
      class_option :mount, type: :string, aliases: "--path", desc: "Taskbar mount path"

      DEFAULT_MOUNT = "/dev/pi-browser-taskbar"
      INITIALIZER_PATH = "config/initializers/pi_browser_taskbar.rb"
      ROUTES_PATH = "config/routes.rb"
      ROUTES_DRAW = /^[ \t]*Rails\.application\.routes\.draw\s+do\b/
      LEGACY_ROUTE = "  mount Pi::Browser::Taskbar::Rails::Engine => \"/dev/pi-browser-taskbar\" if Rails.env.development? && defined?(Pi::Browser::Taskbar::Rails::Engine) && Pi::Browser::Taskbar::Rails.active?"
      LEGACY_LAYOUT = "  <%= Pi::Browser::Taskbar::Rails.layout_bootstrap(self) if Rails.env.development? && defined?(Pi::Browser::Taskbar::Rails) && Pi::Browser::Taskbar::Rails.active? %>"
      LEGACY_INITIALIZER = <<~RUBY.freeze
        # Generated by pi-browser-taskbar-rails. The gem belongs in the development group.
        if Rails.env.development? && defined?(Pi::Browser::Taskbar::Rails)
          Pi::Browser::Taskbar::Rails.configure do |config|
            config.project_root = Rails.root.to_s
          end
        end
      RUBY

      def install
        result = if behavior == :revoke
          self.class.uninstall!(destination_root)
        else
          self.class.run!(destination_root, layout: options[:layout], mount: options[:mount])
        end

        if behavior == :revoke
          say_status result == :current ? :current : :removed, "Pi Browser Taskbar Rails integration"
          say "Remove the pi-browser-taskbar-rails development-group dependency manually if no longer needed."
          say "Broker runtime artifacts, Pi sessions, credentials, and unrelated Action View configuration were not removed."
        else
          say_status result == :current ? :current : :installed, "Pi Browser Taskbar Rails integration"
        end
      rescue ArgumentError => error
        raise ::Rails::Generators::Error, error.message
      end

      class << self
        def run!(root, layout: nil, mount: nil)
          apply!(plan!(root, layout: layout, mount: mount)) ? :installed : :current
        end

        def uninstall!(root)
          apply!(plan_uninstall!(root)) ? :uninstalled : :current
        end

        # Plans and validates every host edit before any write occurs.
        def plan!(root, layout: nil, mount: nil)
          root = canonical_root!(root)
          initializer_path = host_path(root, INITIALIZER_PATH, "initializer")
          installed = File.exist?(initializer_path) ? installed_metadata!(root, initializer_path) : nil
          desired_mount = normalize_mount!(mount || (installed && installed.fetch("mount")) || DEFAULT_MOUNT)

          if installed && desired_mount != installed.fetch("mount")
            raise ArgumentError, "installed mount #{installed.fetch("mount")} differs from #{desired_mount}; run the inverse generator before changing --mount"
          end

          route_path = host_path(root, installed ? installed.fetch("routes") : ROUTES_PATH, "routes metadata")
          selected_layout = layout && explicit_layout!(root, layout)
          layouts = if installed
            installed.fetch("layouts").map { |path| host_path(root, path, "layout metadata") }
          else
            [selected_layout || discover_layout!(root)]
          end
          layouts << selected_layout if selected_layout
          layouts.uniq!

          route_source = read!(route_path, "routes")
          validate_ruby!(route_source, route_path, "routes")
          route_output = install_routes!(route_source, desired_mount)
          validate_ruby!(route_output, route_path, "generated routes")

          layout_outputs = layouts.to_h do |path|
            source = read!(path, "ERB application layout")
            [path, install_layout!(source, desired_mount, path)]
          end

          metadata = {
            "schema" => 1,
            "routes" => relative(route_path, root),
            "layouts" => layouts.map { |path| relative(path, root) },
            "mount" => desired_mount
          }
          initializer_output = initializer_source(metadata)
          validate_ruby!(initializer_output, initializer_path, "generated initializer")

          {route_path => route_output, **layout_outputs, initializer_path => initializer_output}
        end

        # Preflights all recorded seams before returning one all-or-nothing removal plan.
        def plan_uninstall!(root)
          root = canonical_root!(root)
          initializer_path = host_path(root, INITIALIZER_PATH, "initializer")
          unless File.exist?(initializer_path)
            if orphaned_seams?(root)
              raise ArgumentError, "installation metadata is missing while generated host sections remain; manual removal: remove only complete pi-browser-taskbar start/end route and layout blocks"
            end
            return {}
          end

          metadata = installed_metadata!(root, initializer_path)
          route_path = host_path(root, metadata.fetch("routes"), "routes metadata")
          route_source = read!(route_path, "routes")
          route_output = metadata["legacy"] ? route_source.sub(LEGACY_ROUTE, "") : remove_owned!(route_source, "routes", :ruby)
          validate_ruby!(route_output, route_path, "routes")

          actions = {initializer_path => :delete, route_path => route_output}
          metadata.fetch("layouts").each do |relative_path|
            path = host_path(root, relative_path, "layout metadata")
            source = read!(path, "ERB application layout")
            actions[path] = metadata["legacy"] ? source.sub(LEGACY_LAYOUT, "") : remove_owned!(source, "layout", :erb)
          end
          actions
        end

        def refresh_initializer_checksum(source)
          pattern = /^# pi-browser-taskbar:checksum [0-9a-f]{64}\n/
          raise ArgumentError, "unrecognized generated initializer; use manual removal" unless source.match?(pattern)
          without_checksum = source.sub(pattern, "")
          source.sub(pattern, "# pi-browser-taskbar:checksum #{Digest::SHA256.hexdigest(without_checksum)}\n")
        end

        private

        def installed_metadata!(root, path)
          source = read!(path, "generated initializer")
          if source == LEGACY_INITIALIZER
            layout = discover_layout!(root)
            routes = read!(host_path(root, ROUTES_PATH, "routes"), "routes")
            layout_source = read!(layout, "ERB application layout")
            unless routes.include?(LEGACY_ROUTE) && layout_source.include?(LEGACY_LAYOUT)
              raise ArgumentError, "legacy taskbar integration is incomplete; manual removal: restore its initializer, route, and layout lines before rerunning"
            end
            return {"schema" => 1, "routes" => ROUTES_PATH, "layouts" => [relative(layout, root)], "mount" => DEFAULT_MOUNT, "legacy" => true}
          end

          match = source.match(/\A# Generated by pi-browser-taskbar-rails\. Do not edit\.\n# pi-browser-taskbar:metadata ([^\n]+)\n# pi-browser-taskbar:checksum ([0-9a-f]{64})\n/)
          unless match && refresh_initializer_checksum(source) == source
            raise ArgumentError, "refusing edited generated initializer #{path}; manual removal: restore the checksummed initializer, then rerun the inverse generator, or remove only the complete marked route and layout blocks"
          end

          metadata = JSON.parse(match[1])
          required = %w[layouts mount routes schema]
          unless metadata.keys.sort == required && metadata["schema"] == 1 && metadata["layouts"].is_a?(Array) && !metadata["layouts"].empty? && metadata["layouts"].all? { |value| value.is_a?(String) }
            raise ArgumentError, "unrecognized installation metadata in #{path}; use manual removal"
          end
          normalize_mount!(metadata["mount"])
          host_path(root, metadata["routes"], "routes metadata")
          metadata["layouts"].each { |value| host_path(root, value, "layout metadata") }
          metadata
        rescue JSON::ParserError
          raise ArgumentError, "unrecognized installation metadata in #{path}; use manual removal"
        end

        def initializer_source(metadata)
          body = <<~RUBY
            # Generated by pi-browser-taskbar-rails. Do not edit.
            # pi-browser-taskbar:metadata #{JSON.generate(metadata)}
            # pi-browser-taskbar:checksum #{"0" * 64}
            # pi-browser-taskbar:start configuration
            if Rails.env.development? && defined?(Pi::Browser::Taskbar::Rails)
              Pi::Browser::Taskbar::Rails.configure do |config|
                config.mount_path = #{metadata.fetch("mount").inspect}
                config.project_root = Rails.root.to_s
              end
            end
            # pi-browser-taskbar:end configuration
          RUBY
          refresh_initializer_checksum(body)
        end

        def install_routes!(source, mount)
          validate_route_shape!(source)
          parsed = owned_block!(source, "routes", :ruby, required: false)
          unowned_source = if parsed
            source.sub(parsed.fetch(:full), "")
          elsif source.include?(LEGACY_ROUTE)
            source.sub(LEGACY_ROUTE, "")
          else
            source
          end
          if unowned_source.match?(/["']#{Regexp.escape(mount)}(?:\/|["'])/)
            raise ArgumentError, "route conflict at #{mount}; pass a different --mount or remove the conflicting host route"
          end

          draw = unowned_source.match(ROUTES_DRAW)
          insertion = draw.end(0)
          if unowned_source[insertion] == "\n"
            insertion += 1
            block = route_block(mount)
          else
            block = "\n#{route_block(mount)}"
          end
          unowned_source.dup.insert(insertion, block)
        end

        def route_block(mount)
          body = "  mount Pi::Browser::Taskbar::Rails::Engine => #{mount.inspect} if Rails.env.development? && defined?(Pi::Browser::Taskbar::Rails::Engine) && Pi::Browser::Taskbar::Rails.active?\n"
          marked_block("routes", :ruby, body)
        end

        def validate_route_shape!(source)
          draws = source.scan(ROUTES_DRAW).length
          unless draws == 1 && source.match?(/\nend\s*\z/)
            raise ArgumentError, "could not find one supported Rails.application.routes.draw block; patch config/routes.rb manually"
          end
        end

        def install_layout!(source, mount, path)
          unless path.end_with?(".html.erb")
            raise ArgumentError, "layout must be an ERB .html.erb file; pass --layout with a supported ERB application layout"
          end
          validate_erb!(source, path)
          parsed = owned_block!(source, "layout", :erb, required: false)
          opens = source.enum_for(:scan, /<head(?:\s[^>]*)?>/i).map { Regexp.last_match.begin(0) }
          closes = source.enum_for(:scan, %r{</head\s*>}i).map { Regexp.last_match.begin(0) }
          unless opens.length == 1 && closes.length == 1 && opens.first < closes.first
            raise ArgumentError, "could not find one unambiguous <head> in #{path}; pass --layout with a conventional ERB layout or add the marked helper block manually"
          end

          unowned_source = if parsed
            source.sub(parsed.fetch(:full), "")
          elsif source.include?(LEGACY_LAYOUT)
            source.sub(LEGACY_LAYOUT, "")
          else
            source
          end
          if unowned_source.match?(/\bpi_browser_taskbar_tags\b|Pi::Browser::Taskbar::Rails\.layout_bootstrap/)
            raise ArgumentError, "unmarked taskbar helper conflict in #{path}; manual removal: keep one deliberate helper call or remove it before installing"
          end

          block = layout_block
          if parsed
            unless parsed.fetch(:start) > opens.first && parsed.fetch(:start) < closes.first
              raise ArgumentError, "edited generated layout section is outside <head>; manual removal: restore the complete marked layout block"
            end
            source.sub(parsed.fetch(:full), block)
          elsif source.include?(LEGACY_LAYOUT)
            source.sub(LEGACY_LAYOUT, block.chomp)
          else
            source.dup.insert(closes.first, block)
          end
        end

        def layout_block
          body = "<%= pi_browser_taskbar_tags if Rails.env.development? && defined?(Pi::Browser::Taskbar::Rails) && Pi::Browser::Taskbar::Rails.active? %>\n"
          marked_block("layout", :erb, body)
        end

        def marked_block(id, kind, body)
          checksum = Digest::SHA256.hexdigest(body)
          if kind == :ruby
            "  # pi-browser-taskbar:start #{id}\n  # pi-browser-taskbar:checksum #{checksum}\n#{body}  # pi-browser-taskbar:end #{id}\n"
          else
            "<%# pi-browser-taskbar:start #{id} %>\n<%# pi-browser-taskbar:checksum #{checksum} %>\n#{body}<%# pi-browser-taskbar:end #{id} %>\n"
          end
        end

        def owned_block!(source, id, kind, required: true)
          open = kind == :ruby ? "# pi-browser-taskbar:start #{id}" : "<%# pi-browser-taskbar:start #{id} %>"
          close = kind == :ruby ? "# pi-browser-taskbar:end #{id}" : "<%# pi-browser-taskbar:end #{id} %>"
          checksum_pattern = kind == :ruby ? "# pi-browser-taskbar:checksum ([0-9a-f]{64})" : "<%# pi-browser-taskbar:checksum ([0-9a-f]{64}) %>"
          pattern = if kind == :ruby
            /(^[ \t]*#{Regexp.escape(open)}\n^[ \t]*#{checksum_pattern}\n)(.*?)(^[ \t]*#{Regexp.escape(close)}\n?)/m
          else
            /(#{Regexp.escape(open)}\n#{checksum_pattern}\n)(.*?)(#{Regexp.escape(close)}\n?)/m
          end
          matches = source.to_enum(:scan, pattern).map { Regexp.last_match }
          marker_counts = [source.scan(Regexp.escape(open)).length, source.scan(Regexp.escape(close)).length]
          if matches.length > 1 || marker_counts[0] != marker_counts[1] || (marker_counts[0] > 0 && matches.empty?)
            edited_section!(id)
          end
          if matches.empty?
            edited_section!(id) if required
            return nil
          end
          match = matches.first
          checksum = match[2]
          body = match[3]
          edited_section!(id) unless Digest::SHA256.hexdigest(body) == checksum
          {full: match[0], body: body, start: match.begin(0)}
        end

        def remove_owned!(source, id, kind)
          parsed = owned_block!(source, id, kind)
          source.sub(parsed.fetch(:full), "")
        end

        def edited_section!(id)
          raise ArgumentError, "edited generated #{id} section is ambiguous; manual removal: restore the complete content between the pi-browser-taskbar:start #{id} and pi-browser-taskbar:end #{id} markers, then rerun the inverse generator"
        end

        def discover_layout!(root)
          application = File.join(root, "config/application.rb")
          if File.file?(application) && File.read(application).match?(/\bconfig\.api_only\s*=\s*true\b/)
            raise ArgumentError, "API-only Rails applications have no conventional ERB layout; create one and pass --layout for deliberate integration"
          end

          candidates = Dir[File.join(root, "app/views/layouts/application.*")].select { |path| File.file?(path) }
          if candidates.length != 1
            raise ArgumentError, "could not discover one conventional application layout; pass --layout with the project-relative .html.erb path"
          end
          unless candidates.first.end_with?(".html.erb")
            raise ArgumentError, "conventional application layout is not ERB; pass --layout with a supported .html.erb layout"
          end
          candidates.first
        end

        def explicit_layout!(root, value)
          path = host_path(root, value, "layout")
          unless path.end_with?(".html.erb")
            raise ArgumentError, "layout must be a project-relative .html.erb file"
          end
          read!(path, "explicit ERB application layout")
          path
        end

        def normalize_mount!(value)
          unless value.is_a?(String)
            raise ArgumentError, "mount must be an absolute application path string"
          end
          mount = value.sub(%r{/+\z}, "")
          segments = mount.split("/")
          valid = mount.match?(%r{\A/[A-Za-z0-9._~-]+(?:/[A-Za-z0-9._~-]+)*\z}) && segments.none? { |segment| segment == "." || segment == ".." }
          return mount if valid
          raise ArgumentError, "mount must be an absolute application path without a scheme, host, query, fragment, percent encoding, or traversal"
        end

        def canonical_root!(root)
          File.realpath(root)
        rescue Errno::ENOENT, Errno::EACCES, Errno::ENOTDIR => error
          raise ArgumentError, "could not read host root #{root}: #{error.message}"
        end

        def host_path(root, value, label)
          unless value.is_a?(String) && !value.empty?
            raise ArgumentError, "#{label} path must be a non-empty string"
          end
          path = File.expand_path(value, root)
          unless path.start_with?(root + File::SEPARATOR)
            raise ArgumentError, "#{label} path must stay below the host root"
          end
          if File.exist?(path)
            path = File.realpath(path)
            unless path.start_with?(root + File::SEPARATOR)
              raise ArgumentError, "#{label} path must not resolve outside the host root"
            end
          end
          path
        rescue Errno::EACCES, Errno::ELOOP => error
          raise ArgumentError, "could not resolve #{label} path: #{error.message}"
        end

        def orphaned_seams?(root)
          routes = File.join(root, ROUTES_PATH)
          return true if File.file?(routes) && File.read(routes).match?(/pi-browser-taskbar:(?:start routes|checksum)|#{Regexp.escape(LEGACY_ROUTE)}/)
          Dir[File.join(root, "app/views/**/*.erb")].any? do |path|
            File.read(path).include?("pi-browser-taskbar:start layout") || File.read(path).include?(LEGACY_LAYOUT)
          end
        end

        def validate_erb!(source, path)
          ruby = "def __pi_browser_taskbar_template__\n#{ERB.new(source).src}\nend"
          RubyVM::InstructionSequence.compile(ruby, path)
        rescue SyntaxError => error
          raise ArgumentError, "unsupported ERB syntax in #{path}: #{error.message.lines.first.to_s.strip}; fix it before installing"
        end

        def validate_ruby!(source, path, label)
          RubyVM::InstructionSequence.compile(source, path)
        rescue SyntaxError => error
          raise ArgumentError, "unsupported #{label} syntax in #{path}: #{error.message.lines.first.to_s.strip}; fix it before installing"
        end

        def read!(path, label)
          File.read(path)
        rescue Errno::ENOENT, Errno::EACCES, Errno::EISDIR => error
          raise ArgumentError, "could not read #{label} at #{path}: #{error.message}"
        end

        def relative(path, root)
          path.delete_prefix(root + File::SEPARATOR)
        end

        def apply!(actions)
          changed = actions.reject { |path, source| source != :delete && File.file?(path) && File.binread(path) == source }
          return false if changed.empty?

          changed.each do |path, _source|
            parent = File.dirname(path)
            raise ArgumentError, "destination directory is missing at #{parent}" unless File.directory?(parent)
            raise ArgumentError, "destination is not a regular file at #{path}" if File.exist?(path) && !File.file?(path)
          end

          originals = changed.to_h do |path, _source|
            [path, File.exist?(path) ? [File.binread(path), File.stat(path).mode] : nil]
          end
          staged = {}
          begin
            changed.each do |path, source|
              next if source == :delete
              temporary = "#{path}.pi-browser-taskbar-#{Process.pid}-#{rand(1_000_000)}"
              File.open(temporary, File::WRONLY | File::CREAT | File::EXCL, originals[path] ? originals[path][1] : 0o644) { |file| file.write(source) }
              staged[path] = temporary
            end
            changed.each do |path, source|
              source == :delete ? File.delete(path) : File.rename(staged.fetch(path), path)
            end
          rescue StandardError
            originals.each do |path, original|
              if original
                File.binwrite(path, original[0])
                File.chmod(original[1], path)
              else
                FileUtils.rm_f(path)
              end
            end
            raise
          ensure
            staged.each_value { |path| FileUtils.rm_f(path) }
          end
          true
        end
      end
    end
  end
end
