# frozen_string_literal: true

require "rails/generators"
require "fileutils"

module PiBrowserTaskbar
  module Generators
    class InstallGenerator < ::Rails::Generators::Base
      desc "Install the development-only Pi Browser Taskbar engine into a conventional ERB application"

      ROUTE = "  mount Pi::Browser::Taskbar::Rails::Engine => \"/dev/pi-browser-taskbar\" if Rails.env.development? && defined?(Pi::Browser::Taskbar::Rails::Engine)"
      LAYOUT = "  <%= Pi::Browser::Taskbar::Rails.layout_bootstrap(self) if Rails.env.development? && defined?(Pi::Browser::Taskbar::Rails) %>"
      INITIALIZER = <<~RUBY.freeze
        # Generated by pi-browser-taskbar-rails. The gem belongs in the development group.
        if Rails.env.development? && defined?(Pi::Browser::Taskbar::Rails)
          Pi::Browser::Taskbar::Rails.configure do |config|
            config.project_root = Rails.root.to_s
          end
        end
      RUBY

      def install
        changes = self.class.plan!(destination_root)
        changes.each do |path, source|
          FileUtils.mkdir_p(File.dirname(path))
          File.write(path, source)
        end
        say_status :installed, "Pi Browser Taskbar development integration"
      end

      def self.plan!(root)
        root = File.expand_path(root)
        routes = File.join(root, "config/routes.rb")
        layout = File.join(root, "app/views/layouts/application.html.erb")
        initializer = File.join(root, "config/initializers/pi_browser_taskbar.rb")
        route_source = read!(routes, "conventional routes")
        layout_source = read!(layout, "conventional ERB application layout")
        initializer_source = File.exist?(initializer) ? File.read(initializer) : nil
        if initializer_source && initializer_source != INITIALIZER
          raise ArgumentError, "refusing to overwrite edited taskbar initializer #{initializer}"
        end

        {
          routes => insert_before_final_end(route_source, ROUTE, "routes draw block"),
          layout => insert_before_body(layout_source, LAYOUT),
          initializer => INITIALIZER
        }
      end

      def self.insert_before_final_end(source, line, label)
        return source if source.include?(line)
        match = source.match(/\nend\s*\z/)
        raise ArgumentError, "could not find unambiguous #{label}" unless match
        source[0...match.begin(0)] + "\n#{line}\n" + source[match.begin(0)..-1]
      end

      def self.insert_before_body(source, line)
        return source if source.include?(line)
        matches = source.enum_for(:scan, %r{</body>}).map { Regexp.last_match.begin(0) }
        raise ArgumentError, "could not find one conventional layout </body>" unless matches.length == 1
        index = matches.first
        source[0...index] + "#{line}\n" + source[index..-1]
      end

      def self.read!(path, label)
        File.read(path)
      rescue Errno::ENOENT
        raise ArgumentError, "could not read #{label} at #{path}"
      end
    end
  end
end
