defmodule PiBrowserTaskbarPhoenix.Installer do
  @moduledoc "Plans and applies the happy-path integration for a conventional Phoenix application."

  @default_mount "/dev/pi-browser-taskbar"

  @doc "Plans every conventional host edit without writing any file."
  @spec plan!(keyword()) :: %{required(String.t()) => String.t()}
  def plan!(opts \\ []) do
    root = opts |> Keyword.get(:root, File.cwd!()) |> Path.expand()
    mix_path = Path.join(root, "mix.exs")
    mix_source = read!(mix_path, "mix.exs")
    otp_app = discover_otp_app!(mix_source)
    base = to_string(otp_app)
    web_module = Macro.camelize(base) <> "Web"

    paths = %{
      integration: Path.join(root, "lib/#{base}_web/pi_browser_taskbar.ex"),
      application: Path.join(root, "lib/#{base}/application.ex"),
      router: Path.join(root, "lib/#{base}_web/router.ex"),
      layout: Path.join(root, "lib/#{base}_web/components/layouts/root.html.heex")
    }

    sources = %{
      application: read!(paths.application, "conventional application module"),
      router: read!(paths.router, "conventional router"),
      layout: read!(paths.layout, "conventional root layout")
    }

    integration = integration_source(web_module, otp_app, @default_mount) |> format_elixir!()
    validate_existing_integration!(paths.integration, integration)

    application = install_supervisor(sources.application, web_module) |> format_elixir!()
    router = install_routes(sources.router, web_module) |> format_elixir!()
    layout = install_layout(sources.layout, web_module)

    %{
      paths.integration => integration,
      paths.application => application,
      paths.router => router,
      paths.layout => layout
    }
  end

  @doc "Writes a fully validated happy-path installation. Re-running it is idempotent."
  @spec run!(keyword()) :: :ok
  def run!(opts \\ []) do
    opts
    |> plan!()
    |> Enum.each(fn {path, source} -> File.write!(path, source) end)

    :ok
  end

  defp discover_otp_app!(source) do
    case Regex.run(~r/\bapp:\s*:([a-z][a-z0-9_]*)\b/, source, capture: :all_but_first) do
      [app] ->
        String.to_atom(app)

      _other ->
        raise ArgumentError, "could not discover one conventional OTP application from mix.exs"
    end
  end

  defp install_supervisor(source, web_module) do
    marker = "#{web_module}.PiBrowserTaskbar"

    if String.contains?(source, marker) do
      source
    else
      endpoint = "      #{web_module}.Endpoint"
      replace_once!(source, endpoint, "      #{marker},\n#{endpoint}", "host endpoint child")
    end
  end

  defp install_routes(source, web_module) do
    marker = "#{web_module}.PiBrowserTaskbar.routes()"

    if String.contains?(source, marker) do
      source
    else
      expected_module = "defmodule #{web_module}.Router do"

      unless String.contains?(source, expected_module) do
        raise ArgumentError, "router does not define #{web_module}.Router"
      end

      insert_before_final_end!(
        source,
        "\n  require #{web_module}.PiBrowserTaskbar\n  #{marker}\n"
      )
    end
  end

  defp install_layout(source, web_module) do
    marker = "#{web_module}.PiBrowserTaskbar.layout_bootstrap()"

    if String.contains?(source, marker) do
      source
    else
      replace_once!(
        source,
        "  </body>",
        "    <%= #{marker} %>\n  </body>",
        "root layout </body>"
      )
    end
  end

  defp integration_source(web_module, otp_app, mount) do
    """
    defmodule #{web_module}.PiBrowserTaskbar do
      @moduledoc "Development-only host integration generated by Pi Browser Taskbar."

      if Mix.env() == :dev and PiBrowserTaskbarPhoenix.Config.enabled?(#{inspect(otp_app)}) do
        @otp_app #{inspect(otp_app)}
        @mount #{inspect(mount)}

        @doc false
        def child_spec(_opts) do
          Supervisor.child_spec(
            {PiBrowserTaskbarPhoenix.Supervisor, otp_app: @otp_app},
            id: __MODULE__
          )
        end

        @doc false
        defmacro routes do
          quote do
            require PiBrowserTaskbarPhoenix.Router
            PiBrowserTaskbarPhoenix.Router.routes_ast(otp_app: unquote(@otp_app), mount: unquote(@mount))
          end
        end

        @doc false
        def layout_bootstrap, do: PiBrowserTaskbarPhoenix.Layout.render(mount: @mount)
      else
        @doc false
        def child_spec(_opts), do: %{id: __MODULE__, start: {__MODULE__, :ignore, []}}

        @doc false
        def ignore, do: :ignore

        @doc false
        defmacro routes, do: quote(do: nil)

        @doc false
        def layout_bootstrap, do: {:safe, ""}
      end
    end
    """
  end

  defp validate_existing_integration!(path, expected) do
    if File.exists?(path) and File.read!(path) != expected do
      raise ArgumentError, "refusing to overwrite edited integration module #{path}"
    end
  end

  defp insert_before_final_end!(source, insertion) do
    case Regex.run(~r/\nend\s*\z/, source, return: :index) do
      [{index, length}] ->
        prefix = binary_part(source, 0, index)
        suffix = binary_part(source, index, length)
        prefix <> insertion <> suffix

      _other ->
        raise ArgumentError, "router has no unambiguous final end"
    end
  end

  defp replace_once!(source, needle, replacement, label) do
    case :binary.matches(source, needle) do
      [{_index, _length}] -> String.replace(source, needle, replacement)
      [] -> raise ArgumentError, "could not find conventional #{label}"
      _many -> raise ArgumentError, "found ambiguous conventional #{label}"
    end
  end

  defp format_elixir!(source) do
    source
    |> Code.format_string!(line_length: 98)
    |> IO.iodata_to_binary()
  rescue
    error in [SyntaxError, TokenMissingError] ->
      raise ArgumentError,
            "generated integration could not be formatted: #{Exception.message(error)}"
  end

  defp read!(path, label) do
    case File.read(path) do
      {:ok, source} -> source
      {:error, reason} -> raise ArgumentError, "could not read #{label} at #{path}: #{reason}"
    end
  end
end
