#!/usr/bin/env node

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");
const version = fs.readFileSync(path.join(root, "VERSION"), "utf8").trim();
const client = fs.readFileSync(
  path.join(root, "packages/browser-client/src/client.js"),
  "utf8",
).trim();
const styles = fs.readFileSync(
  path.join(root, "packages/browser-client/src/client.css"),
  "utf8",
).trim();

const adapters = [
  {
    framework: "rails",
    provider: "packages/rails/browser/context_provider.js",
    javascript: "packages/rails/lib/pi/browser/taskbar/rails/assets/pi_browser_taskbar.js",
    stylesheet: "packages/rails/lib/pi/browser/taskbar/rails/assets/pi_browser_taskbar.css",
  },
  {
    framework: "phoenix",
    provider: "packages/phoenix/browser/context_provider.js",
    javascript: "packages/phoenix/priv/static/pi_browser_taskbar.js",
    stylesheet: "packages/phoenix/priv/static/pi_browser_taskbar.css",
  },
];

function javascriptFor(adapter) {
  const provider = fs.readFileSync(path.join(root, adapter.provider), "utf8").trim();

  return `/* Generated by tooling/build_browser_assets.mjs. Do not edit. */
(() => {
  "use strict";

${client
  .split("\n")
  .map((line) => (line.length > 0 ? `  ${line}` : ""))
  .join("\n")}

  const taskbarStyles = ${JSON.stringify(styles)};
  const contextProvider = ${provider};
  const client = createBrowserClient({
    contractVersion: 1,
    contextProvider,
    framework: "${adapter.framework}",
    productVersion: "${version}",
  });

  globalThis.PiBrowserTaskbar = Object.freeze({
    contractVersion: 1,
    framework: "${adapter.framework}",
    mount: client.mount,
    productVersion: "${version}",
  });

  const bootstrap = globalThis.document?.querySelector?.("[data-pi-browser-taskbar-bootstrap]");
  if (bootstrap) {
    client.mount({
      csrfToken: bootstrap.dataset.csrfToken,
      mountBase: bootstrap.dataset.mountBase,
      projectApp: bootstrap.dataset.projectApp,
      remoteAccess: bootstrap.dataset.remoteAccess === "true",
    });
  }
})();
`;
}

function stylesheetFor() {
  return `/* Generated by tooling/build_browser_assets.mjs. Do not edit. */\n${styles}\n`;
}

function update(relativePath, expected) {
  const destination = path.join(root, relativePath);
  const actual = fs.existsSync(destination) ? fs.readFileSync(destination, "utf8") : null;

  if (check) {
    if (actual !== expected) {
      console.error(`stale generated browser asset: ${relativePath}`);
      process.exitCode = 1;
    }
    return;
  }

  fs.mkdirSync(path.dirname(destination), { recursive: true });
  fs.writeFileSync(destination, expected);
  console.log(`generated ${relativePath}`);
}

for (const adapter of adapters) {
  update(adapter.javascript, javascriptFor(adapter));
  update(adapter.stylesheet, stylesheetFor());
}

if (check && !process.exitCode) {
  console.log("browser assets are current");
}
